# Generated by Django 3.2.15 on 2022-09-14 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='categories',
        ),
    ]
